name: Deploy to Development and Stage

on:
  push:
    branches: [main]

jobs:
  deploy-development:
    uses: ./.github/workflows/ecs-deploy-reusable.yml
    with:
      github_environment: development
      env_key: dev
      build_image: true
    secrets: inherit

  deploy-stage:
    needs: deploy-development
    uses: ./.github/workflows/ecs-deploy-reusable.yml
    with:
      github_environment: stage
      env_key: stage
      build_image: false
      image_tag: dev-latest
    secrets: inherit
